### ISSUE TITLE
create auction API error 

### ISSUE THREAD

**Issue by ali6600alamdari** [Mehdi-MosTafavi/Saku-Backend#17]
"saku_category" , "saku_tag" does not exist.
![image](https://user-images.githubusercontent.com/56224968/165595724-28b8ef3b-2689-4d02-866d-b66c9ceddc71.png)
@Mehdi-MosTafavi

**Comment by Mehdi-MosTafavi** [comment]
مشکل مایگریشن هست. یه بار دیتابیس باید پاک بشه تا ردیف بشه احتمالا
