### ISSUE TITLE
Get Profile Data API , Unauthorized Error 

### ISSUE THREAD

**Issue by ali6600alamdari** [Mehdi-MosTafavi/Saku-Backend#18]
senario: first login by swagger interface then call profile API :
![image](https://user-images.githubusercontent.com/56224968/165596981-bf44567f-1a03-4ed6-8dfd-d8887e6b61d0.png)

@ @ShahrzadAzari

**Comment by ShahrzadAzari** [comment]
I made some changes and resolve this issue.
You can now authorize your user after logging in and getting access token, like the image below:

![authorize](https://user-images.githubusercontent.com/56067208/165716367-8be0c0bf-d20b-42d8-8201-44ae9bfff3bd.png)

@ali6600alamdari
